/* Auto-generated from raphael-publish theme definitions. */

export interface BuiltinThemeDef {
  name: string;
  className: string;
  desc: string;
  author: string;
  css: string;
}

export const raphaelBuiltinThemes: BuiltinThemeDef[] = [
  {
    "name": "Raphael Mac",
    "className": "raphael-apple",
    "desc": "纯净现代的极致留白，适合日常记录的万能首选",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1d1d1f !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #1d1d1f !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #000 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #1d1d1f !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #f5f5f7 !important; border-left: 4px solid #0066cc; color: #555 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f7 !important; color: #0066cc !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f5f5f7 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f5f5f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1d1d1f !important; border: 1px solid #e0e0e0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #e0e0e0; color: #1d1d1f !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Claude",
    "className": "raphael-claude",
    "desc": "温润的燕麦卡其色底，适合深度长文或文学哲思",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2b2b2b !important; background-color: #f8f6f0 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #b75c3d !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #b75c3d !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2b2b !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #b75c3d !important; background-color: rgba(183,92,61,0.08); padding:0 4px; border-radius:4px;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #b75c3d !important; text-decoration: none; border-bottom: 1px solid #b75c3d; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #2b2b2b !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: rgba(183, 92, 61, 0.04) !important; border-left: 4px solid #b75c3d; color: #555 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0ece4 !important; color: #b75c3d !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0ece4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f0ece4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2b2b !important; border: 1px solid #e0ddd6;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #e0ddd6; color: #2b2b2b !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 微信公众号原生",
    "className": "raphael-wechat",
    "desc": "原汁原味的官方绿底纹，满足传统阅读习惯的稳妥之选",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael NYT",
    "className": "raphael-media",
    "desc": "经典米黄色新闻纸，极强的严肃深度报道专业感",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #000000 !important; background-color: #fdfaf6 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; border-bottom: 2px solid #000; padding-bottom:12px;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #000000 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #000 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #326891 !important; text-decoration: none; border-bottom: 1px solid #326891; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #000000 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #f0ede8 !important; border-left: 4px solid #326891; color: #555 !important; border-radius: 4px; font-style: italic;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0ede8 !important; color: #326891 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0ede8 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #d5cfc5 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f0ede8 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #000000 !important; border: 1px solid #d5cfc5;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #d5cfc5; color: #000000 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Medium",
    "className": "raphael-medium",
    "desc": "简约柔和的西式博客排版，适合生活志与随笔沉淀",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.85 !important; color: #242424 !important; background-color: #fcfcfc !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 24px 0 !important; line-height: 1.85 !important; color: #242424 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #000 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #1a8917 !important; text-decoration: none; border-bottom: 1px solid #1a8917; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 10px 0; line-height: 1.85 !important; color: #242424 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: transparent !important; border-left: 3px solid #1a8917; color: #555 !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f2f3f5 !important; color: #1a8917 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f2f3f5 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f2f3f5 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #242424 !important; border: 1px solid #e0e0e0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #e0e0e0; color: #242424 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Stripe",
    "className": "raphael-stripe",
    "desc": "前沿的硅谷极客商务风，高悬浮感与高亮视觉系",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #425466 !important; background-color: #f6f9fc !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #425466 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #0a2540 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #635bff !important; text-decoration: none; border-bottom: 1px solid #635bff; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #425466 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #eef0ff !important; border-left: 4px solid #635bff; color: #425466 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f2fe !important; color: #635bff !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0f2fe !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #e0e0e0 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f0f2fe !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #425466 !important; border: 1px solid #dde0f0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #dde0f0; color: #425466 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 飞书效率",
    "className": "raphael-workspace",
    "desc": "沉稳严谨的深蓝配色，适合职场效率与管理方法论",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1f2329 !important; background-color: #f7f8fa !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px; border-bottom: 2px solid #3370ff; padding-bottom: 8px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #1f2329 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #1f2329 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #1f2329 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #000 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #3370ff !important; text-decoration: none; border-bottom: 1px solid #3370ff; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #1f2329 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #edf1ff !important; border-left: 4px solid #3370ff; color: #555 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #eef1f8 !important; color: #3370ff !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #eef1f8 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #dee0e3 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #eef1f8 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1f2329 !important; border: 1px solid #dee0e3;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #dee0e3; color: #1f2329 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Linear",
    "className": "raphael-linear",
    "desc": "纯正的暗夜赛博极客风，编程教程与开发日志的终极归宿",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f1f1f2 !important; background-color: #101114 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #f1f1f2 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #f1f1f2 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #fff !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #bbb !important;\n}\n\n.note-to-mp a {\n  color: #5e6ad2 !important; text-decoration: none; border-bottom: 1px solid #5e6ad2; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #f1f1f2 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #1a1a1a !important; border-left: 4px solid #5e6ad2; color: #ccc !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #1a1a2e !important; color: #5e6ad2 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #1a1a2e !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #1a1a2e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #f1f1f2 !important; border: 1px solid #333;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #333; color: #f1f1f2 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Retro",
    "className": "raphael-retro",
    "desc": "做旧羊皮纸搭配火漆红，适合人文历史与艺术鉴赏",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #2b2621 !important; background-color: #f4ecd8 !important; background-image: radial-gradient(circle at center, #f4ecd8 0%, #ebdec4 100%); word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 36px; font-weight: 800; color: #2b2621 !important; line-height: 1.2 !important; margin: 38px 0 20px; letter-spacing: -0.02em; font-variant: small-caps;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 700; color: #8c2211 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2621 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #8c2211 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #8c2211 !important; text-decoration: none; border-bottom: 1px solid #8c2211; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #2b2621 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #efe5cc !important; border-left: 4px solid #8c2211; color: #555 !important; border-radius: 4px; font-style: italic;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #ede4d0 !important; color: #8c2211 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #ede4d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #d4c9ae !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #ede4d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2621 !important; border: 1px solid #d4c9ae;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #d4c9ae; color: #2b2621 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Bloomberg",
    "className": "raphael-bloomberg",
    "desc": "还原华尔街古老金融终端机，硬派科技代码展示专属",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Courier New\", Courier, monospace; font-size: 16px; line-height: 1.7 !important; color: #15fa52 !important; background-color: #000000 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #15fa52 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #15fa52 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #bbb !important;\n}\n\n.note-to-mp a {\n  color: #ff8c00 !important; text-decoration: none; border-bottom: 1px solid #ff8c00; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #15fa52 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #0a0a0a !important; border: 1px solid #333; color: #ccc !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #0a0a0a !important; color: #ff8c00 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #0a0a0a !important; border: 1px solid #333; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #0a0a0a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #15fa52 !important; border: 1px solid #333;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #333; color: #15fa52 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Notion",
    "className": "raphael-notion",
    "desc": "极致克制的黑白灰，纯粹信息密度与无干扰写作",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;\n}\n\n.note-to-mp p {\n  margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #37352f !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #37352f !important;\n}\n\n.note-to-mp a {\n  color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);\n}\n\n.note-to-mp ul {\n  margin: 4px 0; padding-left: 26px;\n}\n\n.note-to-mp ol {\n  margin: 4px 0; padding-left: 26px;\n}\n\n.note-to-mp li {\n  margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;\n}\n\n.note-to-mp blockquote {\n  margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;\n}\n\n.note-to-mp td {\n  padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael GitHub",
    "className": "raphael-github",
    "desc": "开发者最熟悉的阅读界面，README 即视感",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;\n}\n\n.note-to-mp h2 {\n  font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;\n}\n\n.note-to-mp h3 {\n  font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;\n}\n\n.note-to-mp h4 {\n  font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;\n}\n\n.note-to-mp p {\n  margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 600; color: #1f2328 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #1f2328 !important;\n}\n\n.note-to-mp a {\n  color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, \"Liberation Mono\", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;\n}\n\n.note-to-mp hr {\n  margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;\n}\n\n.note-to-mp td {\n  padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 少数派",
    "className": "raphael-sspai",
    "desc": "中文数字媒体标杆，经典红色标识与精致排版",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;\n}\n\n.note-to-mp h2 {\n  font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;\n}\n\n.note-to-mp h3 {\n  font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 12px;\n}\n\n.note-to-mp h4 {\n  font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #d71a1b !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #666 !important;\n}\n\n.note-to-mp a {\n  color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.8 !important; color: #333333 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Dracula",
    "className": "raphael-dracula",
    "desc": "暗紫色赛博吸血鬼美学，粉青撞色的视觉冲击",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #ffb86c !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #8be9fd !important;\n}\n\n.note-to-mp a {\n  color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Nord",
    "className": "raphael-nord",
    "desc": "北欧极地冰霜蓝，冷静克制的极光美学",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #d8dee9 !important; background-color: #2e3440 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #88c0d0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #81a1c1 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #88c0d0 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #d8dee9 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #d8dee9 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #eceff4 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #a3be8c !important;\n}\n\n.note-to-mp a {\n  color: #88c0d0 !important; text-decoration: none; border-bottom: 1px solid #88c0d0; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #d8dee9 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #3b4252 !important; border-left: 4px solid #5e81ac; color: #d8dee9 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #3b4252 !important; color: #a3be8c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #3b4252 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #4c566a !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #3b4252 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #88c0d0 !important; border: 1px solid #4c566a;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #4c566a; color: #d8dee9 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 樱花",
    "className": "raphael-sakura",
    "desc": "柔粉色系日式美学，温柔感性的少女心表达",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a3f4f !important; background-color: #fef7f9 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #c44569 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #c44569 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.75 !important; color: #4a3f4f !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #c44569 !important; background-color: rgba(196,69,105,0.06); padding: 0 4px; border-radius: 4px;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #9b7fa7 !important;\n}\n\n.note-to-mp a {\n  color: #c44569 !important; text-decoration: none; border-bottom: 1px solid rgba(196,69,105,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.75 !important; color: #4a3f4f !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #fceef2 !important; border-left: 4px solid #e8a0b4; color: #6b5570 !important; border-radius: 8px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #fceef2 !important; color: #c44569 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #fceef2 !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #f0d4dd !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #fceef2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a3f4f !important; border: 1px solid #f0d4dd;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #f0d4dd; color: #4a3f4f !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 深海",
    "className": "raphael-ocean",
    "desc": "午夜深蓝配珊瑚橘，沉浸式的海洋系叙事感",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #c8d6e5 !important; background-color: #0c2233 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #ff6b6b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #feca57 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #54a0ff !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #c8d6e5 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #c8d6e5 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #feca57 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #78e0a0 !important;\n}\n\n.note-to-mp a {\n  color: #ff6b6b !important; text-decoration: none; border-bottom: 1px solid #ff6b6b; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #c8d6e5 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #152d42 !important; border-left: 4px solid #54a0ff; color: #c8d6e5 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #152d42 !important; color: #ff6b6b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #152d42 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #1e3a52 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #152d42 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #feca57 !important; border: 1px solid #1e3a52;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #1e3a52; color: #c8d6e5 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 薄荷",
    "className": "raphael-mint",
    "desc": "清凉薄荷绿底色，适合生活方式与健康类内容",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2d4a3e !important; background-color: #f0faf5 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #1a7a5a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #1a7a5a !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #2d4a3e !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #1a7a5a !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #5a8a72 !important;\n}\n\n.note-to-mp a {\n  color: #1a7a5a !important; text-decoration: none; border-bottom: 1px solid rgba(26,122,90,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #2d4a3e !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #e0f5ec !important; border-left: 4px solid #1a7a5a; color: #3d5a4e !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #e0f5ec !important; color: #1a7a5a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #e0f5ec !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #c8e6d8 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #e0f5ec !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2d4a3e !important; border: 1px solid #c8e6d8;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #c8e6d8; color: #2d4a3e !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 日落",
    "className": "raphael-sunset",
    "desc": "暖琥珀色调的黄昏意境，散文游记与情感表达",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #3d2c1e !important; background-color: #fdf6ee !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #c0582a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #c0582a !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 20px 0 !important; line-height: 1.8 !important; color: #3d2c1e !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #c0582a !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #8a6d4b !important;\n}\n\n.note-to-mp a {\n  color: #c0582a !important; text-decoration: none; border-bottom: 1px solid rgba(192,88,42,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.8 !important; color: #3d2c1e !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #f8ead6 !important; border-left: 4px solid #e8a65d; color: #5a4232 !important; border-radius: 4px; font-style: italic;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f5e6d0 !important; color: #c0582a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f5e6d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #e8d4b8 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f5e6d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d2c1e !important; border: 1px solid #e8d4b8;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #e8d4b8; color: #3d2c1e !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Monokai",
    "className": "raphael-monokai",
    "desc": "经典代码编辑器配色，程序员的终极浪漫",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #272822 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 30px; font-weight: 700; color: #f92672 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;\n}\n\n.note-to-mp h2 {\n  font-size: 24px; font-weight: 600; color: #a6e22e !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 20px; font-weight: 600; color: #e6db74 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 17px; font-weight: 600; color: #66d9ef !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #f92672 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #e6db74 !important;\n}\n\n.note-to-mp a {\n  color: #66d9ef !important; text-decoration: none; border-bottom: 1px solid #66d9ef; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #3e3d32 !important; border-left: 4px solid #f92672; color: #a6a68a !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; padding: 3px 6px; background-color: #3e3d32 !important; color: #a6e22e !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #3e3d32 !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #49483e !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;\n}\n\n.note-to-mp th {\n  background-color: #3e3d32 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #a6e22e !important; border: 1px solid #49483e;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #49483e; color: #f8f8f2 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Solarized",
    "className": "raphael-solarized",
    "desc": "经典暖色调开发者配色，柔和护眼的阅读体验",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #657b83 !important; background-color: #fdf6e3 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #cb4b16 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #268bd2 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #2aa198 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #657b83 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #657b83 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #cb4b16 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #93a1a1 !important;\n}\n\n.note-to-mp a {\n  color: #268bd2 !important; text-decoration: none; border-bottom: 1px solid #268bd2; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #657b83 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #eee8d5 !important; border-left: 4px solid #2aa198; color: #586e75 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #eee8d5 !important; color: #859900 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #eee8d5 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #eee8d5 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #eee8d5 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #657b83 !important; border: 1px solid #ddd6c1;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #ddd6c1; color: #657b83 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Cyberpunk",
    "className": "raphael-cyberpunk",
    "desc": "霓虹闪烁的赛博朋克世界，品红与青的极致碰撞",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #e0e0ff !important; background-color: #0d0221 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 8px rgba(255,42,109,0.5); line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: 0.05em; text-transform: uppercase;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #05d9e8 !important; text-shadow: 0 0 8px rgba(5,217,232,0.5); line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #d1f7ff !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #ff2a6d !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #e0e0ff !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 6px rgba(255,42,109,0.4);\n}\n\n.note-to-mp em {\n  font-style: italic; color: #05d9e8 !important;\n}\n\n.note-to-mp a {\n  color: #05d9e8 !important; text-decoration: none; border-bottom: 1px solid #05d9e8; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #e0e0ff !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #1a0a3e !important; border-left: 4px solid #ff2a6d; color: #c8c8ff !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; padding: 3px 6px; background-color: #1a0a3e !important; color: #05d9e8 !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #1a0a3e !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #ff2a6d, #05d9e8) !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;\n}\n\n.note-to-mp th {\n  background-color: #1a0a3e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #ff2a6d !important; border: 1px solid #2a1a4e;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #2a1a4e; color: #e0e0ff !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 水墨",
    "className": "raphael-ink",
    "desc": "纯粹的黑白水墨风，零色彩干扰的极简阅读",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #111111 !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #000000 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.02em; border-bottom: 2px solid #000; padding-bottom: 10px;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 700; color: #000000 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #222222 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 20px 0 !important; line-height: 1.8 !important; color: #111111 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #000000 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #555555 !important;\n}\n\n.note-to-mp a {\n  color: #111111 !important; text-decoration: underline; text-underline-offset: 3px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.8 !important; color: #111111 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: transparent !important; border-left: 3px solid #000000; color: #333333 !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f0f0 !important; color: #000000 !important; border-radius: 2px; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f5f5f5 !important; border-radius: 2px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #e0e0e0;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #000000 !important; width: 40%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f5f5f5 !important; padding: 12px 16px; text-align: left; font-weight: 700; color: #000000 !important; border: 1px solid #cccccc;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #cccccc; color: #111111 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 薰衣草",
    "className": "raphael-lavender",
    "desc": "梦幻紫色调的浪漫氛围，诗意与灵感的温柔表达",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #3d3155 !important; background-color: #f5f0ff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #6b4c9a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #7c5cad !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #3d3155 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #3d3155 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.75 !important; color: #3d3155 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #6b4c9a !important; background-color: rgba(107,76,154,0.08); padding: 0 4px; border-radius: 4px;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #8a6dba !important;\n}\n\n.note-to-mp a {\n  color: #6b4c9a !important; text-decoration: none; border-bottom: 1px solid rgba(107,76,154,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.75 !important; color: #3d3155 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #ece4ff !important; border-left: 4px solid #9b7fd4; color: #5a4570 !important; border-radius: 8px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #ece4ff !important; color: #6b4c9a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #ece4ff !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #ddd0f0 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #ece4ff !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d3155 !important; border: 1px solid #ddd0f0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #ddd0f0; color: #3d3155 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 密林",
    "className": "raphael-forest",
    "desc": "深邃的暗绿色丛林，自然与神秘感的沉浸式叙事",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #c8dcc8 !important; background-color: #1a2e1a !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #7dce82 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #a8d8a8 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #8fbc8f !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #c8dcc8 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #c8dcc8 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #7dce82 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #a0c8a0 !important;\n}\n\n.note-to-mp a {\n  color: #7dce82 !important; text-decoration: none; border-bottom: 1px solid #7dce82; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #c8dcc8 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #243824 !important; border-left: 4px solid #4a8b4a; color: #a8c8a8 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #243824 !important; color: #7dce82 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #243824 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #3a5a3a !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #243824 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #7dce82 !important; border: 1px solid #3a5a3a;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #3a5a3a; color: #c8dcc8 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 冰川",
    "className": "raphael-glacier",
    "desc": "清冽的冰蓝色调，冷静理性的科技分析与报告",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2c3e50 !important; background-color: #eef4fa !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #1565c0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #1976d2 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #2c3e50 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #1565c0 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #5a7a9a !important;\n}\n\n.note-to-mp a {\n  color: #1976d2 !important; text-decoration: none; border-bottom: 1px solid rgba(25,118,210,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #2c3e50 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #e1eef6 !important; border-left: 4px solid #42a5f5; color: #3a5068 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #e1eef6 !important; color: #1565c0 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #e1eef6 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #c8dce8 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #e1eef6 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2c3e50 !important; border: 1px solid #c8dce8;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #c8dce8; color: #2c3e50 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 咖啡",
    "className": "raphael-coffee",
    "desc": "醇厚巧克力棕色调，午后咖啡馆的温暖书卷气",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.75 !important; color: #3e2723 !important; background-color: #f5efe6 !important; background-image: radial-gradient(circle at center, #f5efe6 0%, #ebe2d3 100%); word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #4e342e !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #5d4037 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #3e2723 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #3e2723 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.75 !important; color: #3e2723 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #4e342e !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #795548 !important;\n}\n\n.note-to-mp a {\n  color: #6d4c41 !important; text-decoration: none; border-bottom: 1px solid rgba(109,76,65,0.3); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.75 !important; color: #3e2723 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #ece2d4 !important; border-left: 4px solid #a1887f; color: #5d4037 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #ece2d4 !important; color: #6d4c41 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #ece2d4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #d7ccc8 !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #ece2d4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3e2723 !important; border: 1px solid #d7ccc8;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #d7ccc8; color: #3e2723 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael Bauhaus",
    "className": "raphael-bauhaus",
    "desc": "包豪斯三原色风格，红蓝黄碰撞的现代主义先锋",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.65 !important; color: #1a1a1a !important; background-color: #ffffff !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 34px; font-weight: 900; color: #e30613 !important; line-height: 1.2 !important; margin: 38px 0 16px; letter-spacing: -0.02em; text-transform: uppercase;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 700; color: #004d9f !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.65 !important; color: #1a1a1a !important;\n}\n\n.note-to-mp strong {\n  font-weight: 900; color: #e30613 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #555 !important;\n}\n\n.note-to-mp a {\n  color: #004d9f !important; text-decoration: none; border-bottom: 2px solid #f5a623; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.65 !important; color: #1a1a1a !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #fff4d6 !important; border-left: 6px solid #f5a623; color: #333 !important; border-radius: 0;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f0f0 !important; color: #004d9f !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0f0f0 !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border-left: 6px solid #e30613;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 3px; background-color: #1a1a1a !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #004d9f !important; padding: 16px 16px; text-align: left; font-weight: 700; color: #ffffff !important; border: 3px solid #1a1a1a;\n}\n\n.note-to-mp td {\n  padding: 16px 16px; border: 3px solid #1a1a1a; color: #1a1a1a !important; font-weight: 500;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 赤铜",
    "className": "raphael-copper",
    "desc": "暗夜中的青铜古韵，深沉温暖的金属质感暗色调",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, \"Times New Roman\", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #d4b896 !important; background-color: #1c1410 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #e8a87c !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #c49070 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #d4b896 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #d4b896 !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.7 !important; color: #d4b896 !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #e8a87c !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #b89878 !important;\n}\n\n.note-to-mp a {\n  color: #e8a87c !important; text-decoration: none; border-bottom: 1px solid #e8a87c; padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.7 !important; color: #d4b896 !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #2a1e16 !important; border-left: 4px solid #b8734a; color: #c0a080 !important; border-radius: 4px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #2a1e16 !important; color: #e8a87c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #2a1e16 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 1px; background-color: #3a2a1e !important; width: 100%;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #2a1e16 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #e8a87c !important; border: 1px solid #3a2a1e;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #3a2a1e; color: #d4b896 !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  },
  {
    "name": "Raphael 彩虹糖",
    "className": "raphael-pastel",
    "desc": "多彩柔和的马卡龙色系，活泼甜美的少年感表达",
    "author": "Raphael Publish",
    "css": ".note-to-mp {\n  max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a4a5a !important; background-color: #fefcf8 !important; word-wrap: break-word;\n}\n\n.note-to-mp h1 {\n  font-size: 32px; font-weight: 700; color: #e07a94 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;\n}\n\n.note-to-mp h2 {\n  font-size: 26px; font-weight: 600; color: #7ab8d0 !important; line-height: 1.35 !important; margin: 32px 0 16px;\n}\n\n.note-to-mp h3 {\n  font-size: 21px; font-weight: 600; color: #85b882 !important; line-height: 1.4 !important; margin: 28px 0 14px;\n}\n\n.note-to-mp h4 {\n  font-size: 18px; font-weight: 600; color: #d4a76a !important; line-height: 1.4 !important; margin: 24px 0 12px;\n}\n\n.note-to-mp p {\n  margin: 18px 0 !important; line-height: 1.75 !important; color: #4a4a5a !important;\n}\n\n.note-to-mp strong {\n  font-weight: 700; color: #e07a94 !important;\n}\n\n.note-to-mp em {\n  font-style: italic; color: #9b8ec4 !important;\n}\n\n.note-to-mp a {\n  color: #7ab8d0 !important; text-decoration: none; border-bottom: 1px solid rgba(122,184,208,0.4); padding-bottom: 1px;\n}\n\n.note-to-mp ul {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp ol {\n  margin: 16px 0; padding-left: 28px;\n}\n\n.note-to-mp li {\n  margin: 8px 0; line-height: 1.75 !important; color: #4a4a5a !important;\n}\n\n.note-to-mp blockquote {\n  margin: 24px 0; padding: 16px 20px; background-color: #f0ecff !important; border-left: 4px solid #b8a9e0; color: #5a5a6a !important; border-radius: 12px;\n}\n\n.note-to-mp code {\n  font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #fff0f3 !important; color: #e07a94 !important; border-radius: 6px; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp pre {\n  margin: 24px 0; padding: 20px; background-color: #f0f7ff !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;\n}\n\n.note-to-mp hr {\n  margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #e07a94, #7ab8d0, #85b882, #d4a76a) !important; width: 100%; border-radius: 2px;\n}\n\n.note-to-mp img {\n  max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;\n}\n\n.note-to-mp table {\n  width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;\n}\n\n.note-to-mp th {\n  background-color: #f0ecff !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a4a5a !important; border: 1px solid #e8e0f0;\n}\n\n.note-to-mp td {\n  padding: 12px 16px; border: 1px solid #e8e0f0; color: #4a4a5a !important;\n}\n\n.note-to-mp tr {\n  border: none;\n}"
  }
];
